# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-27 04:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190227_0410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(upload_to='static/images/uploads/users'),
        ),
    ]
