# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-01 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190301_0218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(blank=True, default='/static/images/default.png', null=True, upload_to='static/images/uploads/users'),
        ),
    ]
