# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-08 02:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useractions', '0006_auto_20190305_0349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lyric',
            name='accept',
            field=models.BooleanField(default=False),
        ),
    ]
