# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-27 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0007_auto_20190227_0412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='singer',
            name='description',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='song',
            name='description',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
