# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-28 03:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0008_auto_20190227_0719'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='urlsong',
            field=models.FileField(default=django.utils.timezone.now, upload_to='static/medias/uploads'),
            preserve_default=False,
        ),
    ]
