# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-01 02:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0009_song_urlsong'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='user',
        ),
        migrations.AddField(
            model_name='category',
            name='photo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='static/images/uploads'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='singer',
            name='photo',
            field=models.ImageField(upload_to='static/images/uploads'),
        ),
        migrations.AlterField(
            model_name='song',
            name='photo',
            field=models.ImageField(upload_to='static/images/uploads'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
