# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-01 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0010_auto_20190301_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='photo',
            field=models.ImageField(blank=True, upload_to='static/images/uploads'),
        ),
        migrations.AlterField(
            model_name='singer',
            name='photo',
            field=models.ImageField(blank=True, upload_to='static/images/uploads'),
        ),
        migrations.AlterField(
            model_name='song',
            name='photo',
            field=models.ImageField(blank=True, upload_to='static/images/uploads'),
        ),
    ]
