# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-05 03:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0015_auto_20190301_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='listening',
            field=models.IntegerField(default=0),
        ),
    ]
