# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-11 03:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0016_song_listening'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cate_songs', to='musics.Category'),
        ),
    ]
